### ISSUE TITLE
segfault in prefilter

### ISSUE THREAD

**Issue by gjoni** [soedinglab/MMseqs2#37]
I'm running uniclust_workflow.sh script on a custom fasta database. The first prefiltering step causes a segmentation fault. GDB output is provided below.

```
(gdb) run prefilter /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/tmp/pref_step_FRAG --max-seqs 4000 --min-ungapped-score 100 --comp-bias-corr 0 -s 1
Starting program: /usr/lusers/aivan/prog/MMseqs2/build/bin/mmseqs prefilter /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/tmp/pref_step_FRAG --max-seqs 4000 --min-ungapped-score 100 --comp-bias-corr 0 -s 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Program call:
/usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db /usr/lusers/aivan/work/isolates/tmp/2017_06/tmp/pref_step_FRAG --max-seqs 4000 --min-ungapped-score 100 --comp-bias-corr 0 -s 1 

MMseqs Version:           	31e25cb081a874f225d443eec307a6254f06a291
Sub Matrix                	blosum62.out
Sensitivity               	1
K-mer size                	0
K-score                   	2147483647
Alphabet size             	21
Max. sequence length      	32000
Query queryProfile        	false
Target queryProfile       	false
Max. results per query    	4000
Offset result             	0
Split DB                  	0
Split mode                	2
Coverage threshold        	0
Compositional bias        	0
Diagonal Scoring          	1
Mask Residues             	1
Minimum Diagonal score    	100
Include identical Seq. Id.	false
Spaced Kmer               	1
No preload                	false
Early exit                	false
Threads                   	28
Verbosity                 	3

Initialising data structures...
Using 28 threads.
Could not find precomputed index. Compute index.
Use kmer size 6 and split 1 using Target split mode.
Needed memory (5939332903 byte) of total memory (269768237056 byte)
Target database: /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db(Size: 1282204)
Substitution matrices...
[New Thread 0x2aaac5d87700 (LWP 8622)]
[New Thread 0x2aaac5f88700 (LWP 8623)]
[New Thread 0x2aaac6189700 (LWP 8624)]
[New Thread 0x2aaac638a700 (LWP 8625)]
[New Thread 0x2aaac658b700 (LWP 8626)]
[New Thread 0x2aaac678c700 (LWP 8627)]
[New Thread 0x2aaac698d700 (LWP 8628)]
[New Thread 0x2aaac6b8e700 (LWP 8629)]
[New Thread 0x2aaac6d8f700 (LWP 8630)]
[New Thread 0x2aaac6f90700 (LWP 8631)]
[New Thread 0x2aaac7191700 (LWP 8632)]
[New Thread 0x2aaac7392700 (LWP 8633)]
[New Thread 0x2aaac7593700 (LWP 8634)]
[New Thread 0x2aaac7794700 (LWP 8635)]
[New Thread 0x2aaac7995700 (LWP 8636)]
[New Thread 0x2aaac7b96700 (LWP 8637)]
[New Thread 0x2aaac7d97700 (LWP 8638)]
[New Thread 0x2aaac7f98700 (LWP 8639)]
[New Thread 0x2aaac8199700 (LWP 8640)]
[New Thread 0x2aaac839a700 (LWP 8641)]
[New Thread 0x2aaac859b700 (LWP 8642)]
[New Thread 0x2aaac879c700 (LWP 8643)]
[New Thread 0x2aaac899d700 (LWP 8644)]
[New Thread 0x2aaac8b9e700 (LWP 8645)]
[New Thread 0x2aaac8d9f700 (LWP 8646)]
[New Thread 0x2aaac8fa0700 (LWP 8647)]
[New Thread 0x2aaac91a1700 (LWP 8648)]
Time for init: 0 h 0 m 2s


Query database: /usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db(size=1282204)
Process prefiltering step 1 of 1

Index table: counting k-mers...
...................................................................................................	1 Mio. sequences processed
............................
Index table: Masked residues: 4639530
Index table: fill...
...................................................................................................	1 Mio. sequences processed
............................
Index table: removing duplicate entries...
Index table init done.

DB statistic
Entries:         75296699
DB Size:         1137909162 (byte)
Avg Kmer Size:   0.877931
Top 10 Kmers
   	YTGTPK		2496
	GPGGTT		2371
	HQSGQR		1210
	AGDYKP		1057
	PHFGRQ		943
	PHLGRQ		837
	DPVLEP		661
	PFADTR		653
	MVQFFP		588
	NGAAHP		585
Min Kmer Size:   0
Empty list: 66045602

Time for index table init: 0 h 0 m 29s


k-mer similarity threshold: 130
k-mer match probability: 0

Starting prefiltering scores calculation (step 1 of 1)
Query db start  1 to 1282204
Target db start  1 to 1282204
Wrong prefiltering result: Query: 1 -> 1361079913	r
Invalid database read for id=1361079913, database index=/usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db.index
Wrong prefiltering result: Query: 71 -> 1361079913	r
Invalid database read for id=getDbKey: local id (1361079913) >= db size (1282204)
1361079913, database index=/usr/lusers/aivan/work/isolates/tmp/2017_06/uniprot_db.index
getDbKey: local id (1361079913) >= db size (1282204)
Wrong prefiltering result: Query: 111 -> 1361079913	r
Invalid database read for id=
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aaac5d87700 (LWP 8622)]
0x00002aaaabb70dcd in __run_exit_handlers () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64 libgcc-4.8.5-4.el7.x86_64 libgomp-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00002aaaabb70dcd in __run_exit_handlers () from /usr/lib64/libc.so.6
#1  0x00002aaaabb70eb5 in exit () from /usr/lib64/libc.so.6
#2  0x00000000005de79f in DBReader<unsigned int>::getDbKey (this=0x8b8f10, id=1361079913) at /usr/lusers/aivan/prog/MMseqs2/src/commons/DBReader.cpp:344
#3  0x0000000000548023 in Prefiltering::writePrefilterOutput (this=0x7fffffffda10, qdbr=0x8b8f10, dbWriter=0x7fffffffcc80, thread_idx=1, id=0, prefResults=..., seqIdOffset=0, diagonalScoring=true, resultOffsetPos=0, maxResults=4000)
    at /usr/lusers/aivan/prog/MMseqs2/src/prefiltering/Prefiltering.cpp:758
#4  0x00000000005494d4 in Prefiltering::runSplit () at /usr/lusers/aivan/prog/MMseqs2/src/prefiltering/Prefiltering.cpp:643
#5  0x00002aaaab4fcde5 in ?? () from /usr/lib64/libgomp.so.1
#6  0x00002aaaab923dc5 in start_thread () from /usr/lib64/libpthread.so.0
#7  0x00002aaaabc2eced in clone () from /usr/lib64/libc.so.6

```

**Comment by milot-mirdita** [comment]
We saw this issue internally too a few days ago. Didn't have time to investigate it.
But I do have another workaround for you :)

Call createindex before each prefilter run, you can delete the index afterwards again to save disk space.

Its a very confusing bug that should not be possible.

**Comment by martin-steinegger** [comment]
You could also use commit a81227565da4e95d233e3bcbd5c0cdc6ada1c14a. 
The bug should not occure with this version. 

@milot-mirdita maybe we should roll back to this commit until we found the bug.

**Comment by milot-mirdita** [comment]
I just commited a possible fix. Could you please test if the crash still happens?

**Comment by gjoni** [comment]
Works fine now!

**Comment by milot-mirdita** [comment]
Glad to hear, this was a tricky one :)
