### ISSUE TITLE
nrtotaxmapping throwing std::bad_alloc

### ISSUE THREAD

**Issue by kthurimella** [soedinglab/MMseqs2#666]
## Expected Behavior

nrtotaxmapping to create a _mapping file

## Current Behavior

When I am running the databases workflow to download the NR database the workflow fails on the nrtotaxmapping step at the end.

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

$ mmseqs nrtotaxmapping tmp/12298358726300512471/pdb.accession2taxid tmp/12298358726300512471/prot.accession2taxid nr_mmseqs/nr_db nr_mmseqs/nr_db_mapping --threads 16 -v 3

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

Reading symbols from mmseqs...
(gdb) r
Starting program: /home/kthurime/mmseqs/bin/mmseqs nrtotaxmapping tmp/12298358726300512471/pdb.accession2taxid tmp/12298358726300512471/prot.accession2taxid nr_mmseqs/nr_db nr_mmseqs/nr_db_mapping --threads 16 -v 3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
nr_mmseqs/nr_db_mapping exists and will be overwritten
nrtotaxmapping tmp/12298358726300512471/pdb.accession2taxid tmp/12298358726300512471/prot.accession2taxid nr_mmseqs/nr_db nr_mmseqs/nr_db_mapping --threads 16 -v 3 

MMseqs Version:	f5b588be54de35876eff90f3694b67e1d00856ef
Threads  	16
Verbosity	3

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
0x00000000008cab0b in raise ()
(gdb) bt
#0  0x00000000008cab0b in raise ()
#1  0x000000000040d7bc in abort ()
#2  0x000000000040ad81 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] ()
#3  0x000000000079460c in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000000000794677 in std::terminate() ()
#5  0x00000000007947d9 in __cxa_throw ()
#6  0x000000000040ad02 in operator new(unsigned long) [clone .cold] ()
#7  0x000000000060ed45 in __gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >::allocate (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/9/ext/new_allocator.h:102
#8  std::allocator_traits<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >::allocate (__a=..., __n=<optimized out>)
    at /usr/include/c++/9/bits/alloc_traits.h:443
#9  std::_Vector_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >::_M_allocate (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/9/bits/stl_vector.h:343
#10 std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >::_M_realloc_insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int&> (this=this@entry=0x7fffffffd290, __position=__position@entry=...)
    at /usr/include/c++/9/bits/vector.tcc:440
#11 0x000000000060c68b in std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >::emplace_back<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int&> (this=0x7fffffffd290)
    at /usr/include/c++/9/bits/stl_iterator.h:803
#12 nrtotaxmapping (argc=<optimized out>, argv=<optimized out>, command=...)
    at /home/vsts/work/1/s/src/util/nrtotaxmapping.cpp:96
#13 0x0000000000426a27 in runCommand (p=0x1288200, argc=argc@entry=8, argv=argv@entry=0x7fffffffe3b8)
    at /home/vsts/work/1/s/src/commons/Application.cpp:40
#14 0x000000000040e501 in main (argc=10, argv=0x7fffffffe3a8)
    at /home/vsts/work/1/s/src/commons/Application.cpp:203

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): f5b588be54de35876eff90f3694b67e1d00856ef
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): AVX2
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): 16 vCPU and 64 GB memory
* Operating system and version: Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1021-gcp x86_64)

**Comment by kthurimella** [comment]
Upgraded system to have more memory and this works. It would be nice if there was a way to chunk the mapping since it's such a large file.
