### ISSUE TITLE
Local mmseqs server fails for proteins with :

### ISSUE THREAD

**Issue by xhejtman** [soedinglab/MMseqs2#692]
## Expected Behavior
Search corretly for multiple proteins

## Current Behavior
If I search for protein like: `MADITDKTAEQLENLNIQDD:KQAATGSESQSVENSSASLYV`, local server fails:
```
2023-04-14 13:43:03,073 Could not get MSA/templates for Seq1: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/opt/python3.9/lib/python3.9/site-packages/colabfold/batch.py", line 1404, in run
    = get_msa_and_templates(jobname, query_sequence, result_dir, msa_mode, use_templates,
  File "/opt/python3.9/lib/python3.9/site-packages/colabfold/batch.py", line 862, in get_msa_and_templates
    paired_a3m_lines = run_mmseqs2(
  File "/opt/python3.9/lib/python3.9/site-packages/colabfold/colabfold.py", line 226, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2023-04-14 13:43:03,075 Done
```

The error does not happen with your public server and also it does not happen if I use `colabfold_search`. It happens only when using server API on a local server. Proteins without `:` work ok even via server API.

I believe the problem is:
```
Apr 14 13:42:56 urga1.cerit-sc.cz msa-server: Input taxonomy database "/dev/shm/colab/db/uniref30_2202_db.idx" is missing files:
Apr 14 13:42:56 urga1.cerit-sc.cz msa-server: - /dev/shm/colab/db/uniref30_2202_db.idx_mapping
Apr 14 13:42:56 urga1.cerit-sc.cz msa-server: - /dev/shm/colab/db/uniref30_2202_db.idx_nodes.dmp
Apr 14 13:42:56 urga1.cerit-sc.cz msa-server: - /dev/shm/colab/db/uniref30_2202_db.idx_names.dmp
Apr 14 13:42:56 urga1.cerit-sc.cz msa-server: - /dev/shm/colab/db/uniref30_2202_db.idx_merged.dmp
```

I have latest: `mmseqs-linux-sse41.tar.gz`

**Comment by milot-mirdita** [comment]
please create the following symlinks:
```
ln -s uniref30_2202_db_mapping uniref30_2202_db.idx_mapping
ln -s uniref30_2202_db_taxonomy uniref30_2202_db.idx_taxonomy
```
I have to fix the database creation script.

**Comment by xhejtman** [comment]
Thank you, it helped.
