### ISSUE TITLE
ARM64 installation issue - M3 chip MacBook Pro

### ISSUE THREAD

**Issue by nicolasginet** [soedinglab/MMseqs2#834]
## Context
I am using PHARROKA (available on Github) to annotate bacteriophage genomes. MMseq2 is a required dependency. It was working perfectly on my MacBook Pro purchased in 2011. I recently switched to a new one (MacBook M3-pro) and it is not working anymore (see the above PHARROKA output involving MMseqs). I am very far from being a developer and I am only a self-taught bioinformatician. I am thus seeking help !

I used Brew to install MMseqs, my OS is Mac OS X Sonoma 14.4.1.

Thanks !

Nico

**Comment by milot-mirdita** [comment]
Is there an error message or anything else? MMseqs2 works fine on my Apple Silicon MacBook

**Comment by milot-mirdita** [comment]
I think something has gone wrong attaching the mentioned output.

**Comment by nicolasginet** [comment]
Hello !

Thank you for your reply. I just ran PHARROKA and got the following message. Hope it will help !

Nico

/Users/Nico/miniforge3/envs/HieVi/bin/pharokka.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('Pharokka==1.7.1')
2024-04-23 09:26:28.672 | INFO     | input_commands:instantiate_dirs:183 - Removing output directory Output/ROSA-like as -f or --force was specified.
2024-04-23 09:26:28.676 | INFO     | __main__:main:95 - Starting Pharokka v1.7.1
2024-04-23 09:26:28.676 | INFO     | __main__:main:96 - Command executed: Namespace(infile='Input/ROSA-like/rosa-like.fasta', outdir='Output/ROSA-like', database='Databases', threads='1', force=True, prefix='Default', locustag='ROSA-like', gene_predictor='default', meta=False, split=False, coding_table='11', evalue='1E-05', fast=False, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=True, terminase_strand='pos', terminase_start='1', skip_extra_annotations=False, skip_mash=False, minced_args='', mash_distance=0.2, citation=False)
2024-04-23 09:26:28.676 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
2024-04-23 09:26:28.676 | INFO     | __main__:main:98 - Written by George Bouras: ***@***.***
2024-04-23 09:26:28.676 | INFO     | __main__:main:100 - Checking database installation in Databases.
2024-04-23 09:26:28.677 | INFO     | __main__:main:103 - All databases have been successfully checked.
2024-04-23 09:26:28.677 | INFO     | __main__:main:119 - Checking dependencies.
2024-04-23 09:26:28.777 | INFO     | input_commands:check_dependencies:379 - Phanotate version found is v1.6.5
2024-04-23 09:26:28.778 | INFO     | input_commands:check_dependencies:388 - Phanotate version is ok.
Traceback (most recent call last):
  File "/Users/Nico/miniforge3/envs/HieVi/bin/pharokka.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/nico/Documents/myCore/Bioinformatics/pharokka/bin/pharokka.py", line 489, in <module>
    main()
  File "/Users/nico/Documents/myCore/Bioinformatics/pharokka/bin/pharokka.py", line 128, in main
    ) = check_dependencies(args.skip_mash)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nico/Documents/myCore/Bioinformatics/pharokka/bin/input_commands.py", line 407, in check_dependencies
    mmseqs_major_version = int(mmseqs_version.split(".")[0])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '15-6f452'

**Comment by milot-mirdita** [comment]
I let @gbouras13, our version string is a bit inconsistent between platforms. Should be fixed soon in pharokka.

**Comment by gbouras13** [comment]
Hi @nicolasginet,

I'm the Pharokka developer - thanks for spotting this. I'll put in a fix soon.

In the meantime @nicolasginet if you just comment out the MMSeqs2 related lines by putting a '#' at the front in `/Users/nico/Documents/myCore/Bioinformatics/pharokka/bin/input_commands.py`  (lines 393-419)

https://github.com/gbouras13/pharokka/blob/947c45685169af20a1aba9f78f682516f33c0611/bin/input_commands.py#L393

then Pharokka should hopefully work for you.

Also feel free to make an issue in Pharokka if the issue persists or you run into a different bug.

George
